name: Searching for LLVM's libs
on:
  create:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  macOS_11_Big_Sur_search:
    runs-on: macos-11.0
    steps:
      - uses: actions/checkout@v2
      - name: Checking if we have "locate"
        run: which locate && sudo launchctl load -w /System/Library/LaunchDaemons/com.apple.locate.plist
      - name: Checking if we have "mdfind"
        run: which mdfind
      - name: Checking if we have "find"
        run: which find
      - name: Searching for libLLVM
        run: locate libLLVM*
  macOS_10_Catalina_search:
    runs-on: macos-10.15
    steps:
      - uses: actions/checkout@v2
      - name: Checking if we have "locate"
        run: which locate && sudo launchctl load -w /System/Library/LaunchDaemons/com.apple.locate.plist
      - name: Checking if we have "mdfind"
        run: which mdfind
      - name: Checking if we have "find"
        run: which find
      - name: Searching for libLLVM
        run: locate libLLVM*
